pipeline {
    agent any
    stages {
        stage('Check Ansible Version') {
            steps {
                script {
                    sh '''
                    # Verificar la versión de Ansible
                    echo "Checking Ansible version..."
                    ansible --version || echo "Ansible is not installed or not in the PATH"
                    '''
                }
            }
        }
    }
}
